//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMSLLC.Listener.Service.Implementation.Alliant.GetDevice {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.alliantenergy.com/AssetManagement/DeviceTestInfo/V1")]
    public partial class FaultNotificationType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string businessComponentIDField;
        
        private System.DateTime reportingDateTimeField;
        
        private bool reportingDateTimeFieldSpecified;
        
        private string[] correctiveActionField;
        
        private FaultMessageType faultMessageField;
        
        private FaultingServiceType faultingServiceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string BusinessComponentID {
            get {
                return this.businessComponentIDField;
            }
            set {
                this.businessComponentIDField = value;
                this.RaisePropertyChanged("BusinessComponentID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime ReportingDateTime {
            get {
                return this.reportingDateTimeField;
            }
            set {
                this.reportingDateTimeField = value;
                this.RaisePropertyChanged("ReportingDateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReportingDateTimeSpecified {
            get {
                return this.reportingDateTimeFieldSpecified;
            }
            set {
                this.reportingDateTimeFieldSpecified = value;
                this.RaisePropertyChanged("ReportingDateTimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CorrectiveAction", Order=2)]
        public string[] CorrectiveAction {
            get {
                return this.correctiveActionField;
            }
            set {
                this.correctiveActionField = value;
                this.RaisePropertyChanged("CorrectiveAction");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public FaultMessageType FaultMessage {
            get {
                return this.faultMessageField;
            }
            set {
                this.faultMessageField = value;
                this.RaisePropertyChanged("FaultMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public FaultingServiceType FaultingService {
            get {
                return this.faultingServiceField;
            }
            set {
                this.faultingServiceField = value;
                this.RaisePropertyChanged("FaultingService");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.alliantenergy.com/AssetManagement/DeviceTestInfo/V1")]
    public partial class FaultMessageType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string[] textField;
        
        private string severityField;
        
        private string[] stackField;
        
        private object applicationFaultDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Text", Order=1)]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("Text");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Severity {
            get {
                return this.severityField;
            }
            set {
                this.severityField = value;
                this.RaisePropertyChanged("Severity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Stack", Order=3)]
        public string[] Stack {
            get {
                return this.stackField;
            }
            set {
                this.stackField = value;
                this.RaisePropertyChanged("Stack");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public object ApplicationFaultData {
            get {
                return this.applicationFaultDataField;
            }
            set {
                this.applicationFaultDataField = value;
                this.RaisePropertyChanged("ApplicationFaultData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.alliantenergy.com/AssetManagement/DeviceTestInfo/V1")]
    public partial class FaultingServiceType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string implementationCodeField;
        
        private string instanceIDField;
        
        private string executionContextIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ImplementationCode {
            get {
                return this.implementationCodeField;
            }
            set {
                this.implementationCodeField = value;
                this.RaisePropertyChanged("ImplementationCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string InstanceID {
            get {
                return this.instanceIDField;
            }
            set {
                this.instanceIDField = value;
                this.RaisePropertyChanged("InstanceID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ExecutionContextID {
            get {
                return this.executionContextIDField;
            }
            set {
                this.executionContextIDField = value;
                this.RaisePropertyChanged("ExecutionContextID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.alliantenergy.com/AssetManagement/DeviceTestInfo/V1")]
    public partial class QueryDeviceTestInfoResponseABMType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string classificationCodeField;
        
        private string testReasonField;
        
        private string newDeviceIndicatorField;
        
        private System.Nullable<System.DateTime> lastTestDateField;
        
        private bool lastTestDateFieldSpecified;
        
        private string lossCompensationCodeFlagField;
        
        private string communicationBoardVersionField;
        
        private string communicationModuleFirmwareVersionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ClassificationCode {
            get {
                return this.classificationCodeField;
            }
            set {
                this.classificationCodeField = value;
                this.RaisePropertyChanged("ClassificationCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string TestReason {
            get {
                return this.testReasonField;
            }
            set {
                this.testReasonField = value;
                this.RaisePropertyChanged("TestReason");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string NewDeviceIndicator {
            get {
                return this.newDeviceIndicatorField;
            }
            set {
                this.newDeviceIndicatorField = value;
                this.RaisePropertyChanged("NewDeviceIndicator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<System.DateTime> LastTestDate {
            get {
                return this.lastTestDateField;
            }
            set {
                this.lastTestDateField = value;
                this.RaisePropertyChanged("LastTestDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LastTestDateSpecified {
            get {
                return this.lastTestDateFieldSpecified;
            }
            set {
                this.lastTestDateFieldSpecified = value;
                this.RaisePropertyChanged("LastTestDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string LossCompensationCodeFlag {
            get {
                return this.lossCompensationCodeFlagField;
            }
            set {
                this.lossCompensationCodeFlagField = value;
                this.RaisePropertyChanged("LossCompensationCodeFlag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string CommunicationBoardVersion {
            get {
                return this.communicationBoardVersionField;
            }
            set {
                this.communicationBoardVersionField = value;
                this.RaisePropertyChanged("CommunicationBoardVersion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string CommunicationModuleFirmwareVersion {
            get {
                return this.communicationModuleFirmwareVersionField;
            }
            set {
                this.communicationModuleFirmwareVersionField = value;
                this.RaisePropertyChanged("CommunicationModuleFirmwareVersion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.alliantenergy.com/AssetManagement/DeviceTestInfo/V1")]
    public partial class QueryDeviceTestInfoABMType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string deviceTypeField;
        
        private string serviceTypeField;
        
        private string deviceNumberField;
        
        private string companyField;
        
        private string testerField;
        
        private string testStandardField;
        
        private string testLocationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DeviceType {
            get {
                return this.deviceTypeField;
            }
            set {
                this.deviceTypeField = value;
                this.RaisePropertyChanged("DeviceType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ServiceType {
            get {
                return this.serviceTypeField;
            }
            set {
                this.serviceTypeField = value;
                this.RaisePropertyChanged("ServiceType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string DeviceNumber {
            get {
                return this.deviceNumberField;
            }
            set {
                this.deviceNumberField = value;
                this.RaisePropertyChanged("DeviceNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Company {
            get {
                return this.companyField;
            }
            set {
                this.companyField = value;
                this.RaisePropertyChanged("Company");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Tester {
            get {
                return this.testerField;
            }
            set {
                this.testerField = value;
                this.RaisePropertyChanged("Tester");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string TestStandard {
            get {
                return this.testStandardField;
            }
            set {
                this.testStandardField = value;
                this.RaisePropertyChanged("TestStandard");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string TestLocation {
            get {
                return this.testLocationField;
            }
            set {
                this.testLocationField = value;
                this.RaisePropertyChanged("TestLocation");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://xmlns.alliantenergy.com/AssetManagement/DeviceTestInfo/V1", ConfigurationName="GetDevice.DeviceTestInfoABCS")]
    public interface DeviceTestInfoABCS {
        
        // CODEGEN: Generating message contract since the operation Query is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://xmlns.alliantenergy.com/DeviceTestInfo/V1/Query", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(AMSLLC.Listener.Service.Implementation.Alliant.GetDevice.FaultNotificationType[]), Action="http://xmlns.alliantenergy.com/DeviceTestInfo/V1/Query", Name="QueryDeviceTestInfoFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AMSLLC.Listener.Service.Implementation.Alliant.GetDevice.QueryResponse Query(AMSLLC.Listener.Service.Implementation.Alliant.GetDevice.QueryRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.alliantenergy.com/AssetManagement/DeviceTestInfo/V1", Order=0)]
        public AMSLLC.Listener.Service.Implementation.Alliant.GetDevice.QueryDeviceTestInfoABMType QueryDeviceTestInfoABM;
        
        public QueryRequest() {
        }
        
        public QueryRequest(AMSLLC.Listener.Service.Implementation.Alliant.GetDevice.QueryDeviceTestInfoABMType QueryDeviceTestInfoABM) {
            this.QueryDeviceTestInfoABM = QueryDeviceTestInfoABM;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.alliantenergy.com/AssetManagement/DeviceTestInfo/V1", Order=0)]
        public AMSLLC.Listener.Service.Implementation.Alliant.GetDevice.QueryDeviceTestInfoResponseABMType QueryDeviceTestInfoResponseABM;
        
        public QueryResponse() {
        }
        
        public QueryResponse(AMSLLC.Listener.Service.Implementation.Alliant.GetDevice.QueryDeviceTestInfoResponseABMType QueryDeviceTestInfoResponseABM) {
            this.QueryDeviceTestInfoResponseABM = QueryDeviceTestInfoResponseABM;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DeviceTestInfoABCSChannel : AMSLLC.Listener.Service.Implementation.Alliant.GetDevice.DeviceTestInfoABCS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DeviceTestInfoABCSClient : System.ServiceModel.ClientBase<AMSLLC.Listener.Service.Implementation.Alliant.GetDevice.DeviceTestInfoABCS>, AMSLLC.Listener.Service.Implementation.Alliant.GetDevice.DeviceTestInfoABCS {
        
        public DeviceTestInfoABCSClient() {
        }
        
        public DeviceTestInfoABCSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DeviceTestInfoABCSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DeviceTestInfoABCSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DeviceTestInfoABCSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AMSLLC.Listener.Service.Implementation.Alliant.GetDevice.QueryResponse AMSLLC.Listener.Service.Implementation.Alliant.GetDevice.DeviceTestInfoABCS.Query(AMSLLC.Listener.Service.Implementation.Alliant.GetDevice.QueryRequest request) {
            return base.Channel.Query(request);
        }
        
        public AMSLLC.Listener.Service.Implementation.Alliant.GetDevice.QueryDeviceTestInfoResponseABMType Query(AMSLLC.Listener.Service.Implementation.Alliant.GetDevice.QueryDeviceTestInfoABMType QueryDeviceTestInfoABM) {
            AMSLLC.Listener.Service.Implementation.Alliant.GetDevice.QueryRequest inValue = new AMSLLC.Listener.Service.Implementation.Alliant.GetDevice.QueryRequest();
            inValue.QueryDeviceTestInfoABM = QueryDeviceTestInfoABM;
            AMSLLC.Listener.Service.Implementation.Alliant.GetDevice.QueryResponse retVal = ((AMSLLC.Listener.Service.Implementation.Alliant.GetDevice.DeviceTestInfoABCS)(this)).Query(inValue);
            return retVal.QueryDeviceTestInfoResponseABM;
        }
    }
}
