// <copyright file="AggregateRoot{TId}.cs" company="Advanced Metering Services LLC">
//     Copyright (c) Advanced Metering Services LLC. All rights reserved.
// </copyright>

namespace AMSLLC.Listener.Domain
{
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Diagnostics.Contracts;

    /// <summary>
    /// Base class for all AgregateRoots
    /// </summary>
    /// <typeparam name="TId">The type of identity.</typeparam>
    public abstract class AggregateRoot<TId> : Entity<TId>, IAggregateRoot
    {
        /// <inheritdoc/>
        public ReadOnlyCollection<IDomainEvent> DomainEvents
        {
            get
            {
                // Events always initialized at least to empty list.
                Contract.Assume(this.Events != null);
                return new ReadOnlyCollection<IDomainEvent>(this.Events);
            }
        }

        /// <summary>
        /// Gets the list of domain events generated by this agregate root.
        /// </summary>
        protected IList<IDomainEvent> Events { get; } = new List<IDomainEvent>();
    }
}
