// <auto-generated>
#pragma warning disable 1591
using System.Collections.Generic;
namespace AMSLLC.Listener.Persistence.WNP.Metadata {
public class ImportExportOptionsTable: ITableInformation {
		/// <summary>
	/// <para />Database Type: int
	/// <para />Is Nullable: False
	/// <para />Is Primary Key: True
	/// </summary>
	public string Owner { get; } = "OWNER";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: False
	/// <para />Is Primary Key: False
	/// </summary>
	public string DefinitionName { get; } = "DEFINITION_NAME";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: False
	/// <para />Is Primary Key: False
	/// </summary>
	public string EquipmentType { get; } = "EQUIPMENT_TYPE";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string DelimitChar { get; } = "DELIMIT_CHAR";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string ExportPathFile1 { get; } = "EXPORT_PATH_FILE1";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string ExportPathFile2 { get; } = "EXPORT_PATH_FILE2";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string WinboardSaveExport { get; } = "WINBOARD_SAVE_EXPORT";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string ExportAppend { get; } = "EXPORT_APPEND";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string ImportPathFile { get; } = "IMPORT_PATH_FILE";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string ScheduleEnable { get; } = "SCHEDULE_ENABLE";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string SchedulePeriod { get; } = "SCHEDULE_PERIOD";
		/// <summary>
	/// <para />Database Type: DateTime
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string ScheduleTime { get; } = "SCHEDULE_TIME";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string ScheduleDay { get; } = "SCHEDULE_DAY";
		/// <summary>
	/// <para />Database Type: int
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string ScheduleFrequency { get; } = "SCHEDULE_FREQUENCY";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string PreExportCommand { get; } = "PRE_EXPORT_COMMAND";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string PostExportCommand { get; } = "POST_EXPORT_COMMAND";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string PreImportCommand { get; } = "PRE_IMPORT_COMMAND";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string PostImportCommand { get; } = "POST_IMPORT_COMMAND";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string DatetimeOnFilename1 { get; } = "datetime_on_filename1";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string DatetimeOnFilename2 { get; } = "datetime_on_filename2";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string ExportToWattnet { get; } = "export_to_wattnet";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string Service { get; } = "SERVICE";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: False
	/// <para />Is Primary Key: False
	/// </summary>
	public string DataviewLayout { get; } = "DATAVIEW_LAYOUT";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string ServiceUrl { get; } = "SERVICE_URL";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string ServiceUid { get; } = "SERVICE_UID";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string ServicePwd { get; } = "SERVICE_PWD";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string AdvancedEditing { get; } = "advanced_editing";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string HasFileHeader { get; } = "has_file_header";
	
	public string RealTableName
	{
		get { return "TIMPORT_EXPORT_OPTIONS".ToUpperInvariant(); }		
	}

	public string FullTableName
	{
		get { return ToString(); }		
	}


	private Dictionary<string, ColumnInformation> columnsLookup = new Dictionary<string, ColumnInformation>() 
	{
				{"Owner", new ColumnInformation() { DataType = "int", ModelName = "Owner", ColumnName = "OWNER"}},
				{"DefinitionName", new ColumnInformation() { DataType = "string", ModelName = "DefinitionName", ColumnName = "DEFINITION_NAME"}},
				{"EquipmentType", new ColumnInformation() { DataType = "string", ModelName = "EquipmentType", ColumnName = "EQUIPMENT_TYPE"}},
				{"DelimitChar", new ColumnInformation() { DataType = "string", ModelName = "DelimitChar", ColumnName = "DELIMIT_CHAR"}},
				{"ExportPathFile1", new ColumnInformation() { DataType = "string", ModelName = "ExportPathFile1", ColumnName = "EXPORT_PATH_FILE1"}},
				{"ExportPathFile2", new ColumnInformation() { DataType = "string", ModelName = "ExportPathFile2", ColumnName = "EXPORT_PATH_FILE2"}},
				{"WinboardSaveExport", new ColumnInformation() { DataType = "string", ModelName = "WinboardSaveExport", ColumnName = "WINBOARD_SAVE_EXPORT"}},
				{"ExportAppend", new ColumnInformation() { DataType = "string", ModelName = "ExportAppend", ColumnName = "EXPORT_APPEND"}},
				{"ImportPathFile", new ColumnInformation() { DataType = "string", ModelName = "ImportPathFile", ColumnName = "IMPORT_PATH_FILE"}},
				{"ScheduleEnable", new ColumnInformation() { DataType = "string", ModelName = "ScheduleEnable", ColumnName = "SCHEDULE_ENABLE"}},
				{"SchedulePeriod", new ColumnInformation() { DataType = "string", ModelName = "SchedulePeriod", ColumnName = "SCHEDULE_PERIOD"}},
				{"ScheduleTime", new ColumnInformation() { DataType = "DateTime", ModelName = "ScheduleTime", ColumnName = "SCHEDULE_TIME"}},
				{"ScheduleDay", new ColumnInformation() { DataType = "string", ModelName = "ScheduleDay", ColumnName = "SCHEDULE_DAY"}},
				{"ScheduleFrequency", new ColumnInformation() { DataType = "int", ModelName = "ScheduleFrequency", ColumnName = "SCHEDULE_FREQUENCY"}},
				{"PreExportCommand", new ColumnInformation() { DataType = "string", ModelName = "PreExportCommand", ColumnName = "PRE_EXPORT_COMMAND"}},
				{"PostExportCommand", new ColumnInformation() { DataType = "string", ModelName = "PostExportCommand", ColumnName = "POST_EXPORT_COMMAND"}},
				{"PreImportCommand", new ColumnInformation() { DataType = "string", ModelName = "PreImportCommand", ColumnName = "PRE_IMPORT_COMMAND"}},
				{"PostImportCommand", new ColumnInformation() { DataType = "string", ModelName = "PostImportCommand", ColumnName = "POST_IMPORT_COMMAND"}},
				{"DatetimeOnFilename1", new ColumnInformation() { DataType = "string", ModelName = "DatetimeOnFilename1", ColumnName = "datetime_on_filename1"}},
				{"DatetimeOnFilename2", new ColumnInformation() { DataType = "string", ModelName = "DatetimeOnFilename2", ColumnName = "datetime_on_filename2"}},
				{"ExportToWattnet", new ColumnInformation() { DataType = "string", ModelName = "ExportToWattnet", ColumnName = "export_to_wattnet"}},
				{"Service", new ColumnInformation() { DataType = "string", ModelName = "Service", ColumnName = "SERVICE"}},
				{"DataviewLayout", new ColumnInformation() { DataType = "string", ModelName = "DataviewLayout", ColumnName = "DATAVIEW_LAYOUT"}},
				{"ServiceUrl", new ColumnInformation() { DataType = "string", ModelName = "ServiceUrl", ColumnName = "SERVICE_URL"}},
				{"ServiceUid", new ColumnInformation() { DataType = "string", ModelName = "ServiceUid", ColumnName = "SERVICE_UID"}},
				{"ServicePwd", new ColumnInformation() { DataType = "string", ModelName = "ServicePwd", ColumnName = "SERVICE_PWD"}},
				{"AdvancedEditing", new ColumnInformation() { DataType = "string", ModelName = "AdvancedEditing", ColumnName = "advanced_editing"}},
				{"HasFileHeader", new ColumnInformation() { DataType = "string", ModelName = "HasFileHeader", ColumnName = "has_file_header"}},
			};

	public override string ToString() 
	{
		return "WNDBA.TIMPORT_EXPORT_OPTIONS";
	}
}
}
#pragma warning restore 1591
