// <auto-generated>
#pragma warning disable 1591
using System.Collections.Generic;
namespace AMSLLC.Listener.Persistence.WNP.Metadata {
public class MeterCodeTable: ITableInformation {
		/// <summary>
	/// <para />Database Type: int
	/// <para />Is Nullable: False
	/// <para />Is Primary Key: True
	/// </summary>
	public string Owner { get; } = "OWNER";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: False
	/// <para />Is Primary Key: False
	/// </summary>
	public string MeterCode { get; } = "METER_CODE";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string CatalogNo { get; } = "CATALOG_NO";
		/// <summary>
	/// <para />Database Type: int
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string WarrantyPeriod { get; } = "WARRANTY_PERIOD";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string StrataName { get; } = "STRATA_NAME";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string SelectionProgram { get; } = "SELECTION_PROGRAM";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string TestProgram { get; } = "TEST_PROGRAM";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string TestPeriod { get; } = "TEST_PERIOD";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string Mfr { get; } = "MFR";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string ModelNo { get; } = "MODEL_NO";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string AuxCode { get; } = "AUX_CODE";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string Form { get; } = "FORM";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string Base { get; } = "BASE";
		/// <summary>
	/// <para />Database Type: double
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string TestVolts { get; } = "TEST_VOLTS";
		/// <summary>
	/// <para />Database Type: double
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string TestAmps { get; } = "TEST_AMPS";
		/// <summary>
	/// <para />Database Type: double
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string Kh { get; } = "KH";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string RegisterRatio { get; } = "REGISTER_RATIO";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string Phase { get; } = "PHASE";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string Wire { get; } = "WIRE";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string AepCode { get; } = "aep_code";
		/// <summary>
	/// <para />Database Type: int
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string KwhDials { get; } = "KWH_DIALS";
		/// <summary>
	/// <para />Database Type: int
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string KwDials { get; } = "KW_DIALS";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string ReadSet { get; } = "READ_SET";
		/// <summary>
	/// <para />Database Type: double
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string DmdValDiv { get; } = "DMD_VAL_DIV";
		/// <summary>
	/// <para />Database Type: double
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string DmdFullScale { get; } = "DMD_FULL_SCALE";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string Interval { get; } = "INTERVAL";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string MeterUser01 { get; } = "METER_USER01";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string MeterUser02 { get; } = "METER_USER02";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string MeterUser03 { get; } = "METER_USER03";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string MeterUser04 { get; } = "METER_USER04";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string MeterUser05 { get; } = "METER_USER05";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string MeterUser06 { get; } = "METER_USER06";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string MeterUser07 { get; } = "METER_USER07";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string MeterUser08 { get; } = "METER_USER08";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string MeterUser09 { get; } = "METER_USER09";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string MeterUser10 { get; } = "METER_USER10";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string MeterUser11 { get; } = "METER_USER11";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string MeterUser12 { get; } = "METER_USER12";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string MeterUser13 { get; } = "METER_USER13";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string MeterUser14 { get; } = "METER_USER14";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string MeterUser15 { get; } = "METER_USER15";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string MeterUser16 { get; } = "METER_USER16";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string MeterUser17 { get; } = "METER_USER17";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string MeterUser18 { get; } = "METER_USER18";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string MeterUser19 { get; } = "METER_USER19";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string MeterUser20 { get; } = "METER_USER20";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string MeterUser21 { get; } = "METER_USER21";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string MeterUser22 { get; } = "METER_USER22";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string MeterUser23 { get; } = "METER_USER23";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string MeterUser24 { get; } = "METER_USER24";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string MeterUser25 { get; } = "METER_USER25";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string MeterUser26 { get; } = "METER_USER26";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string MeterUser27 { get; } = "METER_USER27";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string MeterUser28 { get; } = "METER_USER28";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string MeterUser29 { get; } = "METER_USER29";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string MeterUser30 { get; } = "METER_USER30";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string MeterUser31 { get; } = "METER_USER31";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string MeterUser32 { get; } = "METER_USER32";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string MeterUser33 { get; } = "METER_USER33";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string MeterUser34 { get; } = "METER_USER34";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string MeterUser35 { get; } = "METER_USER35";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string MeterUser36 { get; } = "METER_USER36";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string MeterUser37 { get; } = "METER_USER37";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string MeterUser38 { get; } = "METER_USER38";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string MeterUser39 { get; } = "METER_USER39";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string MeterUser40 { get; } = "METER_USER40";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string MeterUser41 { get; } = "METER_USER41";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string MeterUser42 { get; } = "METER_USER42";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string MeterUser43 { get; } = "METER_USER43";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string MeterUser44 { get; } = "METER_USER44";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string MeterUser45 { get; } = "METER_USER45";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string MeterUser46 { get; } = "METER_USER46";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string MeterUser47 { get; } = "METER_USER47";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string MeterUser48 { get; } = "METER_USER48";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string MeterUser49 { get; } = "METER_USER49";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string MeterUser50 { get; } = "METER_USER50";
		/// <summary>
	/// <para />Database Type: DateTime
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string CreateDate { get; } = "CREATE_DATE";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string CreateBy { get; } = "CREATE_BY";
		/// <summary>
	/// <para />Database Type: DateTime
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string ModDate { get; } = "MOD_DATE";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string ModBy { get; } = "MOD_BY";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string AcceptTestPercent { get; } = "accept_test_percent";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string CurrentProgramId { get; } = "current_program_id";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string CurrentFirmwareRev01 { get; } = "CURRENT_FIRMWARE_REV01";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string CurrentFirmwareRev02 { get; } = "CURRENT_FIRMWARE_REV02";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string CurrentFirmwareRev04 { get; } = "CURRENT_FIRMWARE_REV04";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string CurrentFirmwareRev03 { get; } = "CURRENT_FIRMWARE_REV03";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string CurrentFirmwareRev05 { get; } = "CURRENT_FIRMWARE_REV05";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string CurrentFirmwareRev06 { get; } = "CURRENT_FIRMWARE_REV06";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string CurrentFirmwareRev07 { get; } = "CURRENT_FIRMWARE_REV07";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string CurrentFirmwareRev08 { get; } = "CURRENT_FIRMWARE_REV08";
		/// <summary>
	/// <para />Database Type: double
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string CountMeterLoad { get; } = "count_meter_load";
		/// <summary>
	/// <para />Database Type: double
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string SumImpedPhaseA { get; } = "sum_imped_phase_a";
		/// <summary>
	/// <para />Database Type: double
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string SumImpedPhaseB { get; } = "sum_imped_phase_b";
		/// <summary>
	/// <para />Database Type: double
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string SumImpedPhaseC { get; } = "sum_imped_phase_c";
		/// <summary>
	/// <para />Database Type: double
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string SumVaPhaseA { get; } = "sum_va_phase_a";
		/// <summary>
	/// <para />Database Type: double
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string SumVaPhaseB { get; } = "sum_va_phase_b";
		/// <summary>
	/// <para />Database Type: double
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string SumVaPhaseC { get; } = "sum_va_phase_c";
		/// <summary>
	/// <para />Database Type: double
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string SumSqImpedPhaseA { get; } = "sum_sq_imped_phase_a";
		/// <summary>
	/// <para />Database Type: double
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string SumSqImpedPhaseB { get; } = "sum_sq_imped_phase_b";
		/// <summary>
	/// <para />Database Type: double
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string SumSqImpedPhaseC { get; } = "sum_sq_imped_phase_c";
		/// <summary>
	/// <para />Database Type: double
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string SumSqVaPhaseA { get; } = "sum_sq_va_phase_a";
		/// <summary>
	/// <para />Database Type: double
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string SumSqVaPhaseB { get; } = "sum_sq_va_phase_b";
		/// <summary>
	/// <para />Database Type: double
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string SumSqVaPhaseC { get; } = "sum_sq_va_phase_c";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string RmaAcceptTestPercent { get; } = "rma_accept_test_percent";
		/// <summary>
	/// <para />Database Type: int
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string MeterClass { get; } = "METER_CLASS";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string IsFirstArticle { get; } = "is_first_article";
	
	public string RealTableName
	{
		get { return "TMETER_CODE".ToUpperInvariant(); }		
	}

	public string FullTableName
	{
		get { return ToString(); }		
	}


	private Dictionary<string, ColumnInformation> columnsLookup = new Dictionary<string, ColumnInformation>() 
	{
				{"Owner", new ColumnInformation() { DataType = "int", ModelName = "Owner", ColumnName = "OWNER"}},
				{"MeterCode", new ColumnInformation() { DataType = "string", ModelName = "MeterCode", ColumnName = "METER_CODE"}},
				{"CatalogNo", new ColumnInformation() { DataType = "string", ModelName = "CatalogNo", ColumnName = "CATALOG_NO"}},
				{"WarrantyPeriod", new ColumnInformation() { DataType = "int", ModelName = "WarrantyPeriod", ColumnName = "WARRANTY_PERIOD"}},
				{"StrataName", new ColumnInformation() { DataType = "string", ModelName = "StrataName", ColumnName = "STRATA_NAME"}},
				{"SelectionProgram", new ColumnInformation() { DataType = "string", ModelName = "SelectionProgram", ColumnName = "SELECTION_PROGRAM"}},
				{"TestProgram", new ColumnInformation() { DataType = "string", ModelName = "TestProgram", ColumnName = "TEST_PROGRAM"}},
				{"TestPeriod", new ColumnInformation() { DataType = "string", ModelName = "TestPeriod", ColumnName = "TEST_PERIOD"}},
				{"Mfr", new ColumnInformation() { DataType = "string", ModelName = "Mfr", ColumnName = "MFR"}},
				{"ModelNo", new ColumnInformation() { DataType = "string", ModelName = "ModelNo", ColumnName = "MODEL_NO"}},
				{"AuxCode", new ColumnInformation() { DataType = "string", ModelName = "AuxCode", ColumnName = "AUX_CODE"}},
				{"Form", new ColumnInformation() { DataType = "string", ModelName = "Form", ColumnName = "FORM"}},
				{"Base", new ColumnInformation() { DataType = "string", ModelName = "Base", ColumnName = "BASE"}},
				{"TestVolts", new ColumnInformation() { DataType = "double", ModelName = "TestVolts", ColumnName = "TEST_VOLTS"}},
				{"TestAmps", new ColumnInformation() { DataType = "double", ModelName = "TestAmps", ColumnName = "TEST_AMPS"}},
				{"Kh", new ColumnInformation() { DataType = "double", ModelName = "Kh", ColumnName = "KH"}},
				{"RegisterRatio", new ColumnInformation() { DataType = "string", ModelName = "RegisterRatio", ColumnName = "REGISTER_RATIO"}},
				{"Phase", new ColumnInformation() { DataType = "string", ModelName = "Phase", ColumnName = "PHASE"}},
				{"Wire", new ColumnInformation() { DataType = "string", ModelName = "Wire", ColumnName = "WIRE"}},
				{"AepCode", new ColumnInformation() { DataType = "string", ModelName = "AepCode", ColumnName = "aep_code"}},
				{"KwhDials", new ColumnInformation() { DataType = "int", ModelName = "KwhDials", ColumnName = "KWH_DIALS"}},
				{"KwDials", new ColumnInformation() { DataType = "int", ModelName = "KwDials", ColumnName = "KW_DIALS"}},
				{"ReadSet", new ColumnInformation() { DataType = "string", ModelName = "ReadSet", ColumnName = "READ_SET"}},
				{"DmdValDiv", new ColumnInformation() { DataType = "double", ModelName = "DmdValDiv", ColumnName = "DMD_VAL_DIV"}},
				{"DmdFullScale", new ColumnInformation() { DataType = "double", ModelName = "DmdFullScale", ColumnName = "DMD_FULL_SCALE"}},
				{"Interval", new ColumnInformation() { DataType = "string", ModelName = "Interval", ColumnName = "INTERVAL"}},
				{"MeterUser01", new ColumnInformation() { DataType = "string", ModelName = "MeterUser01", ColumnName = "METER_USER01"}},
				{"MeterUser02", new ColumnInformation() { DataType = "string", ModelName = "MeterUser02", ColumnName = "METER_USER02"}},
				{"MeterUser03", new ColumnInformation() { DataType = "string", ModelName = "MeterUser03", ColumnName = "METER_USER03"}},
				{"MeterUser04", new ColumnInformation() { DataType = "string", ModelName = "MeterUser04", ColumnName = "METER_USER04"}},
				{"MeterUser05", new ColumnInformation() { DataType = "string", ModelName = "MeterUser05", ColumnName = "METER_USER05"}},
				{"MeterUser06", new ColumnInformation() { DataType = "string", ModelName = "MeterUser06", ColumnName = "METER_USER06"}},
				{"MeterUser07", new ColumnInformation() { DataType = "string", ModelName = "MeterUser07", ColumnName = "METER_USER07"}},
				{"MeterUser08", new ColumnInformation() { DataType = "string", ModelName = "MeterUser08", ColumnName = "METER_USER08"}},
				{"MeterUser09", new ColumnInformation() { DataType = "string", ModelName = "MeterUser09", ColumnName = "METER_USER09"}},
				{"MeterUser10", new ColumnInformation() { DataType = "string", ModelName = "MeterUser10", ColumnName = "METER_USER10"}},
				{"MeterUser11", new ColumnInformation() { DataType = "string", ModelName = "MeterUser11", ColumnName = "METER_USER11"}},
				{"MeterUser12", new ColumnInformation() { DataType = "string", ModelName = "MeterUser12", ColumnName = "METER_USER12"}},
				{"MeterUser13", new ColumnInformation() { DataType = "string", ModelName = "MeterUser13", ColumnName = "METER_USER13"}},
				{"MeterUser14", new ColumnInformation() { DataType = "string", ModelName = "MeterUser14", ColumnName = "METER_USER14"}},
				{"MeterUser15", new ColumnInformation() { DataType = "string", ModelName = "MeterUser15", ColumnName = "METER_USER15"}},
				{"MeterUser16", new ColumnInformation() { DataType = "string", ModelName = "MeterUser16", ColumnName = "METER_USER16"}},
				{"MeterUser17", new ColumnInformation() { DataType = "string", ModelName = "MeterUser17", ColumnName = "METER_USER17"}},
				{"MeterUser18", new ColumnInformation() { DataType = "string", ModelName = "MeterUser18", ColumnName = "METER_USER18"}},
				{"MeterUser19", new ColumnInformation() { DataType = "string", ModelName = "MeterUser19", ColumnName = "METER_USER19"}},
				{"MeterUser20", new ColumnInformation() { DataType = "string", ModelName = "MeterUser20", ColumnName = "METER_USER20"}},
				{"MeterUser21", new ColumnInformation() { DataType = "string", ModelName = "MeterUser21", ColumnName = "METER_USER21"}},
				{"MeterUser22", new ColumnInformation() { DataType = "string", ModelName = "MeterUser22", ColumnName = "METER_USER22"}},
				{"MeterUser23", new ColumnInformation() { DataType = "string", ModelName = "MeterUser23", ColumnName = "METER_USER23"}},
				{"MeterUser24", new ColumnInformation() { DataType = "string", ModelName = "MeterUser24", ColumnName = "METER_USER24"}},
				{"MeterUser25", new ColumnInformation() { DataType = "string", ModelName = "MeterUser25", ColumnName = "METER_USER25"}},
				{"MeterUser26", new ColumnInformation() { DataType = "string", ModelName = "MeterUser26", ColumnName = "METER_USER26"}},
				{"MeterUser27", new ColumnInformation() { DataType = "string", ModelName = "MeterUser27", ColumnName = "METER_USER27"}},
				{"MeterUser28", new ColumnInformation() { DataType = "string", ModelName = "MeterUser28", ColumnName = "METER_USER28"}},
				{"MeterUser29", new ColumnInformation() { DataType = "string", ModelName = "MeterUser29", ColumnName = "METER_USER29"}},
				{"MeterUser30", new ColumnInformation() { DataType = "string", ModelName = "MeterUser30", ColumnName = "METER_USER30"}},
				{"MeterUser31", new ColumnInformation() { DataType = "string", ModelName = "MeterUser31", ColumnName = "METER_USER31"}},
				{"MeterUser32", new ColumnInformation() { DataType = "string", ModelName = "MeterUser32", ColumnName = "METER_USER32"}},
				{"MeterUser33", new ColumnInformation() { DataType = "string", ModelName = "MeterUser33", ColumnName = "METER_USER33"}},
				{"MeterUser34", new ColumnInformation() { DataType = "string", ModelName = "MeterUser34", ColumnName = "METER_USER34"}},
				{"MeterUser35", new ColumnInformation() { DataType = "string", ModelName = "MeterUser35", ColumnName = "METER_USER35"}},
				{"MeterUser36", new ColumnInformation() { DataType = "string", ModelName = "MeterUser36", ColumnName = "METER_USER36"}},
				{"MeterUser37", new ColumnInformation() { DataType = "string", ModelName = "MeterUser37", ColumnName = "METER_USER37"}},
				{"MeterUser38", new ColumnInformation() { DataType = "string", ModelName = "MeterUser38", ColumnName = "METER_USER38"}},
				{"MeterUser39", new ColumnInformation() { DataType = "string", ModelName = "MeterUser39", ColumnName = "METER_USER39"}},
				{"MeterUser40", new ColumnInformation() { DataType = "string", ModelName = "MeterUser40", ColumnName = "METER_USER40"}},
				{"MeterUser41", new ColumnInformation() { DataType = "string", ModelName = "MeterUser41", ColumnName = "METER_USER41"}},
				{"MeterUser42", new ColumnInformation() { DataType = "string", ModelName = "MeterUser42", ColumnName = "METER_USER42"}},
				{"MeterUser43", new ColumnInformation() { DataType = "string", ModelName = "MeterUser43", ColumnName = "METER_USER43"}},
				{"MeterUser44", new ColumnInformation() { DataType = "string", ModelName = "MeterUser44", ColumnName = "METER_USER44"}},
				{"MeterUser45", new ColumnInformation() { DataType = "string", ModelName = "MeterUser45", ColumnName = "METER_USER45"}},
				{"MeterUser46", new ColumnInformation() { DataType = "string", ModelName = "MeterUser46", ColumnName = "METER_USER46"}},
				{"MeterUser47", new ColumnInformation() { DataType = "string", ModelName = "MeterUser47", ColumnName = "METER_USER47"}},
				{"MeterUser48", new ColumnInformation() { DataType = "string", ModelName = "MeterUser48", ColumnName = "METER_USER48"}},
				{"MeterUser49", new ColumnInformation() { DataType = "string", ModelName = "MeterUser49", ColumnName = "METER_USER49"}},
				{"MeterUser50", new ColumnInformation() { DataType = "string", ModelName = "MeterUser50", ColumnName = "METER_USER50"}},
				{"CreateDate", new ColumnInformation() { DataType = "DateTime", ModelName = "CreateDate", ColumnName = "CREATE_DATE"}},
				{"CreateBy", new ColumnInformation() { DataType = "string", ModelName = "CreateBy", ColumnName = "CREATE_BY"}},
				{"ModDate", new ColumnInformation() { DataType = "DateTime", ModelName = "ModDate", ColumnName = "MOD_DATE"}},
				{"ModBy", new ColumnInformation() { DataType = "string", ModelName = "ModBy", ColumnName = "MOD_BY"}},
				{"AcceptTestPercent", new ColumnInformation() { DataType = "string", ModelName = "AcceptTestPercent", ColumnName = "accept_test_percent"}},
				{"CurrentProgramId", new ColumnInformation() { DataType = "string", ModelName = "CurrentProgramId", ColumnName = "current_program_id"}},
				{"CurrentFirmwareRev01", new ColumnInformation() { DataType = "string", ModelName = "CurrentFirmwareRev01", ColumnName = "CURRENT_FIRMWARE_REV01"}},
				{"CurrentFirmwareRev02", new ColumnInformation() { DataType = "string", ModelName = "CurrentFirmwareRev02", ColumnName = "CURRENT_FIRMWARE_REV02"}},
				{"CurrentFirmwareRev04", new ColumnInformation() { DataType = "string", ModelName = "CurrentFirmwareRev04", ColumnName = "CURRENT_FIRMWARE_REV04"}},
				{"CurrentFirmwareRev03", new ColumnInformation() { DataType = "string", ModelName = "CurrentFirmwareRev03", ColumnName = "CURRENT_FIRMWARE_REV03"}},
				{"CurrentFirmwareRev05", new ColumnInformation() { DataType = "string", ModelName = "CurrentFirmwareRev05", ColumnName = "CURRENT_FIRMWARE_REV05"}},
				{"CurrentFirmwareRev06", new ColumnInformation() { DataType = "string", ModelName = "CurrentFirmwareRev06", ColumnName = "CURRENT_FIRMWARE_REV06"}},
				{"CurrentFirmwareRev07", new ColumnInformation() { DataType = "string", ModelName = "CurrentFirmwareRev07", ColumnName = "CURRENT_FIRMWARE_REV07"}},
				{"CurrentFirmwareRev08", new ColumnInformation() { DataType = "string", ModelName = "CurrentFirmwareRev08", ColumnName = "CURRENT_FIRMWARE_REV08"}},
				{"CountMeterLoad", new ColumnInformation() { DataType = "double", ModelName = "CountMeterLoad", ColumnName = "count_meter_load"}},
				{"SumImpedPhaseA", new ColumnInformation() { DataType = "double", ModelName = "SumImpedPhaseA", ColumnName = "sum_imped_phase_a"}},
				{"SumImpedPhaseB", new ColumnInformation() { DataType = "double", ModelName = "SumImpedPhaseB", ColumnName = "sum_imped_phase_b"}},
				{"SumImpedPhaseC", new ColumnInformation() { DataType = "double", ModelName = "SumImpedPhaseC", ColumnName = "sum_imped_phase_c"}},
				{"SumVaPhaseA", new ColumnInformation() { DataType = "double", ModelName = "SumVaPhaseA", ColumnName = "sum_va_phase_a"}},
				{"SumVaPhaseB", new ColumnInformation() { DataType = "double", ModelName = "SumVaPhaseB", ColumnName = "sum_va_phase_b"}},
				{"SumVaPhaseC", new ColumnInformation() { DataType = "double", ModelName = "SumVaPhaseC", ColumnName = "sum_va_phase_c"}},
				{"SumSqImpedPhaseA", new ColumnInformation() { DataType = "double", ModelName = "SumSqImpedPhaseA", ColumnName = "sum_sq_imped_phase_a"}},
				{"SumSqImpedPhaseB", new ColumnInformation() { DataType = "double", ModelName = "SumSqImpedPhaseB", ColumnName = "sum_sq_imped_phase_b"}},
				{"SumSqImpedPhaseC", new ColumnInformation() { DataType = "double", ModelName = "SumSqImpedPhaseC", ColumnName = "sum_sq_imped_phase_c"}},
				{"SumSqVaPhaseA", new ColumnInformation() { DataType = "double", ModelName = "SumSqVaPhaseA", ColumnName = "sum_sq_va_phase_a"}},
				{"SumSqVaPhaseB", new ColumnInformation() { DataType = "double", ModelName = "SumSqVaPhaseB", ColumnName = "sum_sq_va_phase_b"}},
				{"SumSqVaPhaseC", new ColumnInformation() { DataType = "double", ModelName = "SumSqVaPhaseC", ColumnName = "sum_sq_va_phase_c"}},
				{"RmaAcceptTestPercent", new ColumnInformation() { DataType = "string", ModelName = "RmaAcceptTestPercent", ColumnName = "rma_accept_test_percent"}},
				{"MeterClass", new ColumnInformation() { DataType = "int", ModelName = "MeterClass", ColumnName = "METER_CLASS"}},
				{"IsFirstArticle", new ColumnInformation() { DataType = "string", ModelName = "IsFirstArticle", ColumnName = "is_first_article"}},
			};

	public override string ToString() 
	{
		return "WNDBA.TMETER_CODE";
	}
}
}
#pragma warning restore 1591
