// <auto-generated>
#pragma warning disable 1591
using System.Collections.Generic;
namespace AMSLLC.Listener.Persistence.WNP.Metadata {
public class SysControlTable: ITableInformation {
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: False
	/// <para />Is Primary Key: True
	/// </summary>
	public string TableIndex { get; } = "table_index";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string DisableLogin { get; } = "disable_login";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string SecurityEnabled { get; } = "security_enabled";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string SecurityUserid { get; } = "security_userid";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string SecurityLevel2nopw { get; } = "security_level2nopw";
		/// <summary>
	/// <para />Database Type: int
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string PasswordChangeInterval { get; } = "password_change_interval";
		/// <summary>
	/// <para />Database Type: int
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string NextBoxNo { get; } = "next_box_no";
		/// <summary>
	/// <para />Database Type: int
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string NextPalletNo { get; } = "next_pallet_no";
		/// <summary>
	/// <para />Database Type: int
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string NextUnknownNo { get; } = "next_unknown_no";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string AutoCreateEquipment { get; } = "auto_create_equipment";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string UseTrackingAtTesting { get; } = "use_tracking_at_testing";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string UseWattnetBasic { get; } = "use_wattnet_basic";
		/// <summary>
	/// <para />Database Type: int
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string NextBatchNo { get; } = "NEXT_BATCH_NO";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string UsesMfrSerialNoFlag { get; } = "USES_MFR_SERIAL_NO_FLAG";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string EnableAutoDbUpdates { get; } = "enable_auto_db_updates";
		/// <summary>
	/// <para />Database Type: int
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string AuditLogNextIndex { get; } = "audit_log_next_index";
		/// <summary>
	/// <para />Database Type: int
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string AuditLogLimit { get; } = "audit_log_limit";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string UseLdapAtLogin { get; } = "use_ldap_at_login";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string LdapServer { get; } = "ldap_server";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string LdapDomainName { get; } = "ldap_domain_name";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string SyslogIpAddr { get; } = "syslog_ip_addr";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string SyslogProtocol { get; } = "syslog_protocol";
	
	public string RealTableName
	{
		get { return "TSYS_CONTROL".ToUpperInvariant(); }		
	}

	public string FullTableName
	{
		get { return ToString(); }		
	}


	private Dictionary<string, ColumnInformation> columnsLookup = new Dictionary<string, ColumnInformation>() 
	{
				{"TableIndex", new ColumnInformation() { DataType = "string", ModelName = "TableIndex", ColumnName = "table_index"}},
				{"DisableLogin", new ColumnInformation() { DataType = "string", ModelName = "DisableLogin", ColumnName = "disable_login"}},
				{"SecurityEnabled", new ColumnInformation() { DataType = "string", ModelName = "SecurityEnabled", ColumnName = "security_enabled"}},
				{"SecurityUserid", new ColumnInformation() { DataType = "string", ModelName = "SecurityUserid", ColumnName = "security_userid"}},
				{"SecurityLevel2nopw", new ColumnInformation() { DataType = "string", ModelName = "SecurityLevel2nopw", ColumnName = "security_level2nopw"}},
				{"PasswordChangeInterval", new ColumnInformation() { DataType = "int", ModelName = "PasswordChangeInterval", ColumnName = "password_change_interval"}},
				{"NextBoxNo", new ColumnInformation() { DataType = "int", ModelName = "NextBoxNo", ColumnName = "next_box_no"}},
				{"NextPalletNo", new ColumnInformation() { DataType = "int", ModelName = "NextPalletNo", ColumnName = "next_pallet_no"}},
				{"NextUnknownNo", new ColumnInformation() { DataType = "int", ModelName = "NextUnknownNo", ColumnName = "next_unknown_no"}},
				{"AutoCreateEquipment", new ColumnInformation() { DataType = "string", ModelName = "AutoCreateEquipment", ColumnName = "auto_create_equipment"}},
				{"UseTrackingAtTesting", new ColumnInformation() { DataType = "string", ModelName = "UseTrackingAtTesting", ColumnName = "use_tracking_at_testing"}},
				{"UseWattnetBasic", new ColumnInformation() { DataType = "string", ModelName = "UseWattnetBasic", ColumnName = "use_wattnet_basic"}},
				{"NextBatchNo", new ColumnInformation() { DataType = "int", ModelName = "NextBatchNo", ColumnName = "NEXT_BATCH_NO"}},
				{"UsesMfrSerialNoFlag", new ColumnInformation() { DataType = "string", ModelName = "UsesMfrSerialNoFlag", ColumnName = "USES_MFR_SERIAL_NO_FLAG"}},
				{"EnableAutoDbUpdates", new ColumnInformation() { DataType = "string", ModelName = "EnableAutoDbUpdates", ColumnName = "enable_auto_db_updates"}},
				{"AuditLogNextIndex", new ColumnInformation() { DataType = "int", ModelName = "AuditLogNextIndex", ColumnName = "audit_log_next_index"}},
				{"AuditLogLimit", new ColumnInformation() { DataType = "int", ModelName = "AuditLogLimit", ColumnName = "audit_log_limit"}},
				{"UseLdapAtLogin", new ColumnInformation() { DataType = "string", ModelName = "UseLdapAtLogin", ColumnName = "use_ldap_at_login"}},
				{"LdapServer", new ColumnInformation() { DataType = "string", ModelName = "LdapServer", ColumnName = "ldap_server"}},
				{"LdapDomainName", new ColumnInformation() { DataType = "string", ModelName = "LdapDomainName", ColumnName = "ldap_domain_name"}},
				{"SyslogIpAddr", new ColumnInformation() { DataType = "string", ModelName = "SyslogIpAddr", ColumnName = "syslog_ip_addr"}},
				{"SyslogProtocol", new ColumnInformation() { DataType = "string", ModelName = "SyslogProtocol", ColumnName = "syslog_protocol"}},
			};

	public override string ToString() 
	{
		return "WNDBA.TSYS_CONTROL";
	}
}
}
#pragma warning restore 1591
