// <auto-generated>
#pragma warning disable 1591
using System.Collections.Generic;
namespace AMSLLC.Listener.Persistence.Metadata {
public class CustomFieldDescriptionsTable: ITableInformation {
		/// <summary>
	/// <para />Database Type: int
	/// <para />Is Nullable: False
	/// <para />Is Primary Key: True
	/// </summary>
	public string Owner { get; } = "OWNER";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: False
	/// <para />Is Primary Key: False
	/// </summary>
	public string EqpType { get; } = "EQP_TYPE";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: False
	/// <para />Is Primary Key: False
	/// </summary>
	public string WecoFieldName { get; } = "WECO_FIELD_NAME";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string CustomerDesc { get; } = "CUSTOMER_DESC";
		/// <summary>
	/// <para />Database Type: int
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string FieldNo { get; } = "FIELD_NO";
		/// <summary>
	/// <para />Database Type: int
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string Width { get; } = "WIDTH";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string Mask { get; } = "MASK";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string ValidationFilter { get; } = "VALIDATION_FILTER";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string InitialValue { get; } = "INITIAL_VALUE";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string ClearOnNewMeter { get; } = "CLEAR_ON_NEW_METER";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string RestoreOnOpen { get; } = "RESTORE_ON_OPEN";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string FilterCol { get; } = "FILTER_COL";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string RequiredField { get; } = "REQUIRED_FIELD";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string ClearFromPrevious { get; } = "CLEAR_FROM_PREVIOUS";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string ReadOnly { get; } = "READ_ONLY";
		/// <summary>
	/// <para />Database Type: int
	/// <para />Is Nullable: False
	/// <para />Is Primary Key: False
	/// </summary>
	public string MinLength { get; } = "min_length";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: False
	/// <para />Is Primary Key: False
	/// </summary>
	public string LayoutName { get; } = "LAYOUT_NAME";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string TableName { get; } = "TABLE_NAME";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string ControlType { get; } = "CONTROL_TYPE";
		/// <summary>
	/// <para />Database Type: int
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string X { get; } = "X";
		/// <summary>
	/// <para />Database Type: int
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string Y { get; } = "Y";
		/// <summary>
	/// <para />Database Type: int
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string ControlWidth { get; } = "CONTROL_WIDTH";
		/// <summary>
	/// <para />Database Type: int
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string ControlHeight { get; } = "CONTROL_HEIGHT";
		/// <summary>
	/// <para />Database Type: byte[]
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string PictureData { get; } = "PICTURE_DATA";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string FontProperties { get; } = "FONT_PROPERTIES";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string Visible { get; } = "VISIBLE";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string ForceCase { get; } = "FORCE_CASE";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string Justify { get; } = "JUSTIFY";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string LeadingZero { get; } = "LEADING_ZERO";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string CharsAllowed { get; } = "CHARS_ALLOWED";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string DbDataType { get; } = "DB_DATA_TYPE";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string CodeControlled { get; } = "CODE_CONTROLLED";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string ValDisplayField { get; } = "VAL_DISPLAY_FIELD";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string ComboboxStyle { get; } = "COMBOBOX_STYLE";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string RequiredOnCreate { get; } = "required_on_create";
	
	public string RealTableName
	{
		get { return "TCUSTOM_FIELD_DESCRIPTIONS".ToUpperInvariant(); }		
	}

	public string FullTableName
	{
		get { return ToString(); }		
	}


	private Dictionary<string, ColumnInformation> columnsLookup = new Dictionary<string, ColumnInformation>() 
	{
				{"Owner", new ColumnInformation() { DataType = "int", ModelName = "Owner", ColumnName = "OWNER"}},
				{"EqpType", new ColumnInformation() { DataType = "string", ModelName = "EqpType", ColumnName = "EQP_TYPE"}},
				{"WecoFieldName", new ColumnInformation() { DataType = "string", ModelName = "WecoFieldName", ColumnName = "WECO_FIELD_NAME"}},
				{"CustomerDesc", new ColumnInformation() { DataType = "string", ModelName = "CustomerDesc", ColumnName = "CUSTOMER_DESC"}},
				{"FieldNo", new ColumnInformation() { DataType = "int", ModelName = "FieldNo", ColumnName = "FIELD_NO"}},
				{"Width", new ColumnInformation() { DataType = "int", ModelName = "Width", ColumnName = "WIDTH"}},
				{"Mask", new ColumnInformation() { DataType = "string", ModelName = "Mask", ColumnName = "MASK"}},
				{"ValidationFilter", new ColumnInformation() { DataType = "string", ModelName = "ValidationFilter", ColumnName = "VALIDATION_FILTER"}},
				{"InitialValue", new ColumnInformation() { DataType = "string", ModelName = "InitialValue", ColumnName = "INITIAL_VALUE"}},
				{"ClearOnNewMeter", new ColumnInformation() { DataType = "string", ModelName = "ClearOnNewMeter", ColumnName = "CLEAR_ON_NEW_METER"}},
				{"RestoreOnOpen", new ColumnInformation() { DataType = "string", ModelName = "RestoreOnOpen", ColumnName = "RESTORE_ON_OPEN"}},
				{"FilterCol", new ColumnInformation() { DataType = "string", ModelName = "FilterCol", ColumnName = "FILTER_COL"}},
				{"RequiredField", new ColumnInformation() { DataType = "string", ModelName = "RequiredField", ColumnName = "REQUIRED_FIELD"}},
				{"ClearFromPrevious", new ColumnInformation() { DataType = "string", ModelName = "ClearFromPrevious", ColumnName = "CLEAR_FROM_PREVIOUS"}},
				{"ReadOnly", new ColumnInformation() { DataType = "string", ModelName = "ReadOnly", ColumnName = "READ_ONLY"}},
				{"MinLength", new ColumnInformation() { DataType = "int", ModelName = "MinLength", ColumnName = "min_length"}},
				{"LayoutName", new ColumnInformation() { DataType = "string", ModelName = "LayoutName", ColumnName = "LAYOUT_NAME"}},
				{"TableName", new ColumnInformation() { DataType = "string", ModelName = "TableName", ColumnName = "TABLE_NAME"}},
				{"ControlType", new ColumnInformation() { DataType = "string", ModelName = "ControlType", ColumnName = "CONTROL_TYPE"}},
				{"X", new ColumnInformation() { DataType = "int", ModelName = "X", ColumnName = "X"}},
				{"Y", new ColumnInformation() { DataType = "int", ModelName = "Y", ColumnName = "Y"}},
				{"ControlWidth", new ColumnInformation() { DataType = "int", ModelName = "ControlWidth", ColumnName = "CONTROL_WIDTH"}},
				{"ControlHeight", new ColumnInformation() { DataType = "int", ModelName = "ControlHeight", ColumnName = "CONTROL_HEIGHT"}},
				{"PictureData", new ColumnInformation() { DataType = "byte[]", ModelName = "PictureData", ColumnName = "PICTURE_DATA"}},
				{"FontProperties", new ColumnInformation() { DataType = "string", ModelName = "FontProperties", ColumnName = "FONT_PROPERTIES"}},
				{"Visible", new ColumnInformation() { DataType = "string", ModelName = "Visible", ColumnName = "VISIBLE"}},
				{"ForceCase", new ColumnInformation() { DataType = "string", ModelName = "ForceCase", ColumnName = "FORCE_CASE"}},
				{"Justify", new ColumnInformation() { DataType = "string", ModelName = "Justify", ColumnName = "JUSTIFY"}},
				{"LeadingZero", new ColumnInformation() { DataType = "string", ModelName = "LeadingZero", ColumnName = "LEADING_ZERO"}},
				{"CharsAllowed", new ColumnInformation() { DataType = "string", ModelName = "CharsAllowed", ColumnName = "CHARS_ALLOWED"}},
				{"DbDataType", new ColumnInformation() { DataType = "string", ModelName = "DbDataType", ColumnName = "DB_DATA_TYPE"}},
				{"CodeControlled", new ColumnInformation() { DataType = "string", ModelName = "CodeControlled", ColumnName = "CODE_CONTROLLED"}},
				{"ValDisplayField", new ColumnInformation() { DataType = "string", ModelName = "ValDisplayField", ColumnName = "VAL_DISPLAY_FIELD"}},
				{"ComboboxStyle", new ColumnInformation() { DataType = "string", ModelName = "ComboboxStyle", ColumnName = "COMBOBOX_STYLE"}},
				{"RequiredOnCreate", new ColumnInformation() { DataType = "string", ModelName = "RequiredOnCreate", ColumnName = "required_on_create"}},
			};

	public override string ToString() 
	{
		return "wndba.tcustom_field_descriptions";
	}
}
}
#pragma warning restore 1591
