// <auto-generated>
#pragma warning disable 1591
using System.Collections.Generic;
namespace AMSLLC.Listener.Persistence.Metadata {
public class DeviceTable: ITableInformation {
		/// <summary>
	/// <para />Database Type: int
	/// <para />Is Nullable: False
	/// <para />Is Primary Key: True
	/// </summary>
	public string DeviceId { get; } = "DeviceId";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string ExternalId { get; } = "ExternalId";
		/// <summary>
	/// <para />Database Type: int
	/// <para />Is Nullable: False
	/// <para />Is Primary Key: False
	/// </summary>
	public string CompanyId { get; } = "CompanyId";
		/// <summary>
	/// <para />Database Type: int
	/// <para />Is Nullable: False
	/// <para />Is Primary Key: False
	/// </summary>
	public string ServiceTypeId { get; } = "ServiceTypeId";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: False
	/// <para />Is Primary Key: False
	/// </summary>
	public string EquipmentNumber { get; } = "EquipmentNumber";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: False
	/// <para />Is Primary Key: False
	/// </summary>
	public string EquipmentType { get; } = "EquipmentType";
	
	public string RealTableName
	{
		get { return "Device".ToUpperInvariant(); }		
	}

	public string FullTableName
	{
		get { return ToString(); }		
	}


	private Dictionary<string, ColumnInformation> columnsLookup = new Dictionary<string, ColumnInformation>() 
	{
				{"DeviceId", new ColumnInformation() { DataType = "int", ModelName = "DeviceId", ColumnName = "DeviceId"}},
				{"ExternalId", new ColumnInformation() { DataType = "string", ModelName = "ExternalId", ColumnName = "ExternalId"}},
				{"CompanyId", new ColumnInformation() { DataType = "int", ModelName = "CompanyId", ColumnName = "CompanyId"}},
				{"ServiceTypeId", new ColumnInformation() { DataType = "int", ModelName = "ServiceTypeId", ColumnName = "ServiceTypeId"}},
				{"EquipmentNumber", new ColumnInformation() { DataType = "string", ModelName = "EquipmentNumber", ColumnName = "EquipmentNumber"}},
				{"EquipmentType", new ColumnInformation() { DataType = "string", ModelName = "EquipmentType", ColumnName = "EquipmentType"}},
			};

	public override string ToString() 
	{
		return "DBO.DEVICE";
	}
}
}
#pragma warning restore 1591
