// <auto-generated>
#pragma warning disable 1591
using System.Collections.Generic;
namespace AMSLLC.Listener.Persistence.Metadata {
public class FirmwareLabelTable: ITableInformation {
		/// <summary>
	/// <para />Database Type: int
	/// <para />Is Nullable: False
	/// <para />Is Primary Key: True
	/// </summary>
	public string Owner { get; } = "owner";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string LabelFirmwareRev01 { get; } = "label_firmware_rev01";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string LabelFirmwareRev02 { get; } = "label_firmware_rev02";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string LabelFirmwareRev03 { get; } = "label_firmware_rev03";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string LabelFirmwareRev04 { get; } = "label_firmware_rev04";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string LabelFirmwareRev05 { get; } = "label_firmware_rev05";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string LabelFirmwareRev06 { get; } = "label_firmware_rev06";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string LabelFirmwareRev07 { get; } = "label_firmware_rev07";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string LabelFirmwareRev08 { get; } = "label_firmware_rev08";
		/// <summary>
	/// <para />Database Type: DateTime
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string CreateDate { get; } = "create_date";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string CreateBy { get; } = "create_by";
		/// <summary>
	/// <para />Database Type: DateTime
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string ModDate { get; } = "mod_date";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string ModBy { get; } = "mod_by";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string ProcessTagRev01 { get; } = "process_tag_rev01";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string ProcessTagRev02 { get; } = "process_tag_rev02";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string ProcessTagRev03 { get; } = "process_tag_rev03";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string ProcessTagRev04 { get; } = "process_tag_rev04";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string ProcessTagRev05 { get; } = "process_tag_rev05";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string ProcessTagRev06 { get; } = "process_tag_rev06";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string ProcessTagRev07 { get; } = "process_tag_rev07";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string ProcessTagRev08 { get; } = "process_tag_rev08";
	
	public string RealTableName
	{
		get { return "tfirmware_label".ToUpperInvariant(); }		
	}

	public string FullTableName
	{
		get { return ToString(); }		
	}


	private Dictionary<string, ColumnInformation> columnsLookup = new Dictionary<string, ColumnInformation>() 
	{
				{"Owner", new ColumnInformation() { DataType = "int", ModelName = "Owner", ColumnName = "owner"}},
				{"LabelFirmwareRev01", new ColumnInformation() { DataType = "string", ModelName = "LabelFirmwareRev01", ColumnName = "label_firmware_rev01"}},
				{"LabelFirmwareRev02", new ColumnInformation() { DataType = "string", ModelName = "LabelFirmwareRev02", ColumnName = "label_firmware_rev02"}},
				{"LabelFirmwareRev03", new ColumnInformation() { DataType = "string", ModelName = "LabelFirmwareRev03", ColumnName = "label_firmware_rev03"}},
				{"LabelFirmwareRev04", new ColumnInformation() { DataType = "string", ModelName = "LabelFirmwareRev04", ColumnName = "label_firmware_rev04"}},
				{"LabelFirmwareRev05", new ColumnInformation() { DataType = "string", ModelName = "LabelFirmwareRev05", ColumnName = "label_firmware_rev05"}},
				{"LabelFirmwareRev06", new ColumnInformation() { DataType = "string", ModelName = "LabelFirmwareRev06", ColumnName = "label_firmware_rev06"}},
				{"LabelFirmwareRev07", new ColumnInformation() { DataType = "string", ModelName = "LabelFirmwareRev07", ColumnName = "label_firmware_rev07"}},
				{"LabelFirmwareRev08", new ColumnInformation() { DataType = "string", ModelName = "LabelFirmwareRev08", ColumnName = "label_firmware_rev08"}},
				{"CreateDate", new ColumnInformation() { DataType = "DateTime", ModelName = "CreateDate", ColumnName = "create_date"}},
				{"CreateBy", new ColumnInformation() { DataType = "string", ModelName = "CreateBy", ColumnName = "create_by"}},
				{"ModDate", new ColumnInformation() { DataType = "DateTime", ModelName = "ModDate", ColumnName = "mod_date"}},
				{"ModBy", new ColumnInformation() { DataType = "string", ModelName = "ModBy", ColumnName = "mod_by"}},
				{"ProcessTagRev01", new ColumnInformation() { DataType = "string", ModelName = "ProcessTagRev01", ColumnName = "process_tag_rev01"}},
				{"ProcessTagRev02", new ColumnInformation() { DataType = "string", ModelName = "ProcessTagRev02", ColumnName = "process_tag_rev02"}},
				{"ProcessTagRev03", new ColumnInformation() { DataType = "string", ModelName = "ProcessTagRev03", ColumnName = "process_tag_rev03"}},
				{"ProcessTagRev04", new ColumnInformation() { DataType = "string", ModelName = "ProcessTagRev04", ColumnName = "process_tag_rev04"}},
				{"ProcessTagRev05", new ColumnInformation() { DataType = "string", ModelName = "ProcessTagRev05", ColumnName = "process_tag_rev05"}},
				{"ProcessTagRev06", new ColumnInformation() { DataType = "string", ModelName = "ProcessTagRev06", ColumnName = "process_tag_rev06"}},
				{"ProcessTagRev07", new ColumnInformation() { DataType = "string", ModelName = "ProcessTagRev07", ColumnName = "process_tag_rev07"}},
				{"ProcessTagRev08", new ColumnInformation() { DataType = "string", ModelName = "ProcessTagRev08", ColumnName = "process_tag_rev08"}},
			};

	public override string ToString() 
	{
		return "WNDBA.TFIRMWARE_LABEL";
	}
}
}
#pragma warning restore 1591
