// <auto-generated>
#pragma warning disable 1591
using System.Collections.Generic;
namespace AMSLLC.Listener.Persistence.Metadata {
public class HarmonicConfigurationTable: ITableInformation {
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: False
	/// <para />Is Primary Key: True
	/// </summary>
	public string ConfigurationName { get; } = "configuration_name";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string Va { get; } = "va";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string Vb { get; } = "vb";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string Vc { get; } = "vc";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string Ia { get; } = "ia";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string Ib { get; } = "ib";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string Ic { get; } = "ic";
		/// <summary>
	/// <para />Database Type: int
	/// <para />Is Nullable: False
	/// <para />Is Primary Key: False
	/// </summary>
	public string Revision { get; } = "revision";
		/// <summary>
	/// <para />Database Type: int
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string VaRevision { get; } = "va_revision";
		/// <summary>
	/// <para />Database Type: int
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string VbRevision { get; } = "vb_revision";
		/// <summary>
	/// <para />Database Type: int
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string VcRevision { get; } = "vc_revision";
		/// <summary>
	/// <para />Database Type: int
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string IaRevision { get; } = "ia_revision";
		/// <summary>
	/// <para />Database Type: int
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string IbRevision { get; } = "ib_revision";
		/// <summary>
	/// <para />Database Type: int
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string IcRevision { get; } = "ic_revision";
	
	public string RealTableName
	{
		get { return "tharmonic_configuration".ToUpperInvariant(); }		
	}

	public string FullTableName
	{
		get { return ToString(); }		
	}


	private Dictionary<string, ColumnInformation> columnsLookup = new Dictionary<string, ColumnInformation>() 
	{
				{"ConfigurationName", new ColumnInformation() { DataType = "string", ModelName = "ConfigurationName", ColumnName = "configuration_name"}},
				{"Va", new ColumnInformation() { DataType = "string", ModelName = "Va", ColumnName = "va"}},
				{"Vb", new ColumnInformation() { DataType = "string", ModelName = "Vb", ColumnName = "vb"}},
				{"Vc", new ColumnInformation() { DataType = "string", ModelName = "Vc", ColumnName = "vc"}},
				{"Ia", new ColumnInformation() { DataType = "string", ModelName = "Ia", ColumnName = "ia"}},
				{"Ib", new ColumnInformation() { DataType = "string", ModelName = "Ib", ColumnName = "ib"}},
				{"Ic", new ColumnInformation() { DataType = "string", ModelName = "Ic", ColumnName = "ic"}},
				{"Revision", new ColumnInformation() { DataType = "int", ModelName = "Revision", ColumnName = "revision"}},
				{"VaRevision", new ColumnInformation() { DataType = "int", ModelName = "VaRevision", ColumnName = "va_revision"}},
				{"VbRevision", new ColumnInformation() { DataType = "int", ModelName = "VbRevision", ColumnName = "vb_revision"}},
				{"VcRevision", new ColumnInformation() { DataType = "int", ModelName = "VcRevision", ColumnName = "vc_revision"}},
				{"IaRevision", new ColumnInformation() { DataType = "int", ModelName = "IaRevision", ColumnName = "ia_revision"}},
				{"IbRevision", new ColumnInformation() { DataType = "int", ModelName = "IbRevision", ColumnName = "ib_revision"}},
				{"IcRevision", new ColumnInformation() { DataType = "int", ModelName = "IcRevision", ColumnName = "ic_revision"}},
			};

	public override string ToString() 
	{
		return "WNDBA.THARMONIC_CONFIGURATION";
	}
}
}
#pragma warning restore 1591
