// <auto-generated>
#pragma warning disable 1591
using System.Collections.Generic;
namespace AMSLLC.Listener.Persistence.Metadata {
public class ShopGoalsTable: ITableInformation {
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: False
	/// <para />Is Primary Key: True
	/// </summary>
	public string EqpType { get; } = "EQP_TYPE";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: False
	/// <para />Is Primary Key: False
	/// </summary>
	public string ShopStatus { get; } = "SHOP_STATUS";
		/// <summary>
	/// <para />Database Type: int
	/// <para />Is Nullable: False
	/// <para />Is Primary Key: False
	/// </summary>
	public string Year { get; } = "YEAR";
		/// <summary>
	/// <para />Database Type: int
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string January { get; } = "JANUARY";
		/// <summary>
	/// <para />Database Type: int
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string February { get; } = "FEBRUARY";
		/// <summary>
	/// <para />Database Type: int
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string March { get; } = "MARCH";
		/// <summary>
	/// <para />Database Type: int
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string April { get; } = "APRIL";
		/// <summary>
	/// <para />Database Type: int
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string May { get; } = "MAY";
		/// <summary>
	/// <para />Database Type: int
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string June { get; } = "JUNE";
		/// <summary>
	/// <para />Database Type: int
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string July { get; } = "JULY";
		/// <summary>
	/// <para />Database Type: int
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string August { get; } = "AUGUST";
		/// <summary>
	/// <para />Database Type: int
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string September { get; } = "SEPTEMBER";
		/// <summary>
	/// <para />Database Type: int
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string October { get; } = "OCTOBER";
		/// <summary>
	/// <para />Database Type: int
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string November { get; } = "NOVEMBER";
		/// <summary>
	/// <para />Database Type: int
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string December { get; } = "DECEMBER";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string ModBy { get; } = "MOD_BY";
		/// <summary>
	/// <para />Database Type: DateTime
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string ModDate { get; } = "MOD_DATE";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string CreateBy { get; } = "CREATE_BY";
		/// <summary>
	/// <para />Database Type: DateTime
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string CreateDate { get; } = "CREATE_DATE";
	
	public string RealTableName
	{
		get { return "TSHOP_GOALS".ToUpperInvariant(); }		
	}

	public string FullTableName
	{
		get { return ToString(); }		
	}


	private Dictionary<string, ColumnInformation> columnsLookup = new Dictionary<string, ColumnInformation>() 
	{
				{"EqpType", new ColumnInformation() { DataType = "string", ModelName = "EqpType", ColumnName = "EQP_TYPE"}},
				{"ShopStatus", new ColumnInformation() { DataType = "string", ModelName = "ShopStatus", ColumnName = "SHOP_STATUS"}},
				{"Year", new ColumnInformation() { DataType = "int", ModelName = "Year", ColumnName = "YEAR"}},
				{"January", new ColumnInformation() { DataType = "int", ModelName = "January", ColumnName = "JANUARY"}},
				{"February", new ColumnInformation() { DataType = "int", ModelName = "February", ColumnName = "FEBRUARY"}},
				{"March", new ColumnInformation() { DataType = "int", ModelName = "March", ColumnName = "MARCH"}},
				{"April", new ColumnInformation() { DataType = "int", ModelName = "April", ColumnName = "APRIL"}},
				{"May", new ColumnInformation() { DataType = "int", ModelName = "May", ColumnName = "MAY"}},
				{"June", new ColumnInformation() { DataType = "int", ModelName = "June", ColumnName = "JUNE"}},
				{"July", new ColumnInformation() { DataType = "int", ModelName = "July", ColumnName = "JULY"}},
				{"August", new ColumnInformation() { DataType = "int", ModelName = "August", ColumnName = "AUGUST"}},
				{"September", new ColumnInformation() { DataType = "int", ModelName = "September", ColumnName = "SEPTEMBER"}},
				{"October", new ColumnInformation() { DataType = "int", ModelName = "October", ColumnName = "OCTOBER"}},
				{"November", new ColumnInformation() { DataType = "int", ModelName = "November", ColumnName = "NOVEMBER"}},
				{"December", new ColumnInformation() { DataType = "int", ModelName = "December", ColumnName = "DECEMBER"}},
				{"ModBy", new ColumnInformation() { DataType = "string", ModelName = "ModBy", ColumnName = "MOD_BY"}},
				{"ModDate", new ColumnInformation() { DataType = "DateTime", ModelName = "ModDate", ColumnName = "MOD_DATE"}},
				{"CreateBy", new ColumnInformation() { DataType = "string", ModelName = "CreateBy", ColumnName = "CREATE_BY"}},
				{"CreateDate", new ColumnInformation() { DataType = "DateTime", ModelName = "CreateDate", ColumnName = "CREATE_DATE"}},
			};

	public override string ToString() 
	{
		return "wndba.tshop_goals";
	}
}
}
#pragma warning restore 1591
