// <auto-generated>
#pragma warning disable 1591
using System.Collections.Generic;
namespace AMSLLC.Listener.Persistence.Metadata {
public class TransactionLogTable: ITableInformation {
		/// <summary>
	/// <para />Database Type: int
	/// <para />Is Nullable: False
	/// <para />Is Primary Key: True
	/// </summary>
	public string TransactionLogId { get; } = "TransactionLogId";
		/// <summary>
	/// <para />Database Type: string
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string ExternalId { get; } = "ExternalId";
		/// <summary>
	/// <para />Database Type: int
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string DeviceId { get; } = "DeviceId";
		/// <summary>
	/// <para />Database Type: int
	/// <para />Is Nullable: True
	/// <para />Is Primary Key: False
	/// </summary>
	public string DeviceTestId { get; } = "DeviceTestId";
		/// <summary>
	/// <para />Database Type: int
	/// <para />Is Nullable: False
	/// <para />Is Primary Key: False
	/// </summary>
	public string TransactionTypeId { get; } = "TransactionTypeId";
		/// <summary>
	/// <para />Database Type: int
	/// <para />Is Nullable: False
	/// <para />Is Primary Key: False
	/// </summary>
	public string TransactionStatusId { get; } = "TransactionStatusId";
		/// <summary>
	/// <para />Database Type: int
	/// <para />Is Nullable: False
	/// <para />Is Primary Key: False
	/// </summary>
	public string TransactionSourceId { get; } = "TransactionSourceId";
	
	public string RealTableName
	{
		get { return "TransactionLog".ToUpperInvariant(); }		
	}

	public string FullTableName
	{
		get { return ToString(); }		
	}


	private Dictionary<string, ColumnInformation> columnsLookup = new Dictionary<string, ColumnInformation>() 
	{
				{"TransactionLogId", new ColumnInformation() { DataType = "int", ModelName = "TransactionLogId", ColumnName = "TransactionLogId"}},
				{"ExternalId", new ColumnInformation() { DataType = "string", ModelName = "ExternalId", ColumnName = "ExternalId"}},
				{"DeviceId", new ColumnInformation() { DataType = "int", ModelName = "DeviceId", ColumnName = "DeviceId"}},
				{"DeviceTestId", new ColumnInformation() { DataType = "int", ModelName = "DeviceTestId", ColumnName = "DeviceTestId"}},
				{"TransactionTypeId", new ColumnInformation() { DataType = "int", ModelName = "TransactionTypeId", ColumnName = "TransactionTypeId"}},
				{"TransactionStatusId", new ColumnInformation() { DataType = "int", ModelName = "TransactionStatusId", ColumnName = "TransactionStatusId"}},
				{"TransactionSourceId", new ColumnInformation() { DataType = "int", ModelName = "TransactionSourceId", ColumnName = "TransactionSourceId"}},
			};

	public override string ToString() 
	{
		return "DBO.TRANSACTIONLOG";
	}
}
}
#pragma warning restore 1591
