//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.18020.
// 
namespace AMSLLC.Listener.Service.Implementation.KCPL.Messages
{
    using System.Xml.Serialization;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class TransactionResponseServiceRequest
    {

        private int listenerTransactionIdField;

        private int statusField;

        private string messageField;

        private string debugInfoField;

        /// <remarks/>
        public int listenerTransactionId
        {
            get
            {
                return this.listenerTransactionIdField;
            }
            set
            {
                this.listenerTransactionIdField = value;
            }
        }

        /// <remarks/>
        public int status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }

        /// <remarks/>
        public string debugInfo
        {
            get
            {
                return this.debugInfoField;
            }
            set
            {
                this.debugInfoField = value;
            }
        }
    }
}
